export { default as DosPlayer } from './DosPlayer'
export { default as Footer } from './Footer'
export { default as GameModal } from './GameModal'
export { default as Header } from './Header'
export { default as LocaleToggle } from './LocaleToggle'
export { default as ThemeToggle } from './ThemeToggle'
export { default as HowWasAchivedGames } from './JsDosAchievement'
export { default as EasterEgg } from './EasterEgg'
